version: '3'
services:
  mariadb:
    image: mariadb:latest
    networks:
      - pay_network
    volumes:
      - ./db/data/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_USER=mariauser
      - MARIADB_PASSWORD=mariapw

  membership-service:
    image: pay-membership-service:1.0.1
    networks:
      - pay_network
    ports:
      - "8081:8080"
    depends_on:
      - mariadb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/pay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MARIADB_USER}
      - SPRING_DATASOURCE_PASSWORD=${MARIADB_PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MariaDBDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

networks:
  pay_network:
    driver: bridge